### PR TITLE
Create Python Package

### PR DESCRIPTION
**Pull request by sschaetz**
### Description

This is an attempt to turn svut into a pip-installable Python package. To accomplish this we

- add a pyproject and setup.py file that describes the package and its entry-points
- move the source-code to a subdir `svut/`
- create main functions in the two files that can be referenced in `setup.py`
- update the links and regression tests

### CODE REVIEW

**Comment by sschaetz** [comment]
You can try this by installing it with:

```bash
pip install "svut @ git+https://github.com/sschaetz/svut/@85d8d5622289979f37cd8f8762a98baefda19d28"
```

**Comment by dpretet** [comment]
Dude, 

everything runs out of the box flawlessly :) I tried the example and one of my other test bench and it's OK on macOS + python v3.10.6, thank you so much!

What's next? How to publish a version now?

**Comment by sschaetz** [comment]
Oh that is great to hear. 🎉 

> How to publish a version now?

This is where I am not exactly sure since I have never done it -- but I would follow these excellent instructions [here](https://realpython.com/pypi-publish-python-package/#publish-your-package-to-pypi). It even comes with a test upload step so you can double-check if it works. I could take a stab at it but since this is your project I think you should give it a shot. Let me know if I can help.

**Comment by dpretet** [comment]
Ok ok I will give a try maybe tonight or most likely this weekend. I'll also check it could be included in a GitHub action.

**Comment by sschaetz** [comment]
Sounds good. I can take a stab at it as well, I don't mind.

**Pull request merged**
